apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.26.1
  values:
    controller:
      ingressClass: nginx
