apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.29.3
  values:
    controller:
      ingressClass: nginx
