apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.cert-manager-controller: glob:~v0.11.*
spec:
  releaseName: cert-manager
  target-namespace: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 0.11.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.11.0
    webhook:
      enabled: false
